pid:
  p: 0.175 #0.160 #0.195
  i: 0.040 #0.035 #0.070
  d: 0.030 #0.170 #0.250
  ff: 0
  dff: 0
  imax: 0.1
limits:
  speed_max_xy: 0.3
  speed_max_z: 0.15
  speed_max_yaw: 0.05
  accel_max_xy: 0.5
  accel_max_z: 0.1
accuracy: 0.70     # 使用像素半径作为目标范围的百分比 单位：1
radius: 0.080      # 到达目标范围内的精度 单位：m
shot_duration: 1.0 # 到达范围内稳定时间后投弹 的持续时间 单位：s
shot_wait: 0.5     # 投弹后等待时间 单位：s
tar_x_l: 700.0     # 左侧舵机 目标x坐标，单位：px  0使用默认值
tar_y_l: 450.0     # 左侧舵机 目标y坐标，单位：px  0使用默认值
tar_x_r: 620.0     # 右侧舵机 目标x坐标，单位：px  0使用默认值
tar_y_r: 450.0     # 右侧舵机 目标y坐标，单位：px  0使用默认值
tar_z: 1.2         # 目标y坐标 单位：m
shot_target_x_l: 0.045 #0.130   # 0.045 # 左侧舵机 相对于飞机坐标 投弹点x坐标，单位：m
shot_target_y_l: 0.0   # 左侧舵机 投弹点y坐标，单位：m
shot_target_z_l: 0.10 # 左侧舵机 投弹点z坐标，单位：m
shot_target_x_r: -0.045 #0.025  # -0.045 # 右侧舵机 投弹点
shot_target_y_r: 0.0   # 右侧舵机 投弹点y坐标，单位：m
shot_target_z_r: 0.10 # 右侧舵机 投弹点 z坐标，单位：m
