pid:
  p: 0.4
  i: 0.10
  d: 0.15
  ff: 0
  dff: 0
  imax: 10
limits:
  speed_max_xy: 0.3
  speed_max_z: 0.2
  speed_max_yaw: 0.1
  accel_max_xy: 0.5
  accel_max_z: 0.1
#
radius: 0.0 # 到达目标范围内的精度 单位：米
accuracy: 0.0   # 使用像素半径作为目标范围的百分比 单位：1
#
land_target_x: 0.0
land_target_y: 0.0
land_target_z: 0.0
#
tar_x: 640.0 # 目标x坐标，单位：px  0使用默认值
tar_y: 400.0 # 目标y坐标，单位：px  0使用默认值
tar_z: 0.2 # 目标z坐标，单位：米
#
scout_x: 0.0 # 投弹搜索点附加x坐标，单位：米
scout_y: 0.0 # 投弹搜索点附加y坐标，单位：米
scout_halt: 3.0 # 侦察点高度，单位：秒