<<<<<<< HEAD
dx_see: 0.0
dx_shot: 5
dy_see: 54.0
dy_shot: 5
headingangle_compass: 0.0
see_halt: 3.0
shot_halt: 5
=======
headingangle_compass: 178.0
dx_shot: 0.0
dy_shot: 30.0
dx_see: 0.0
dx_shot: 10
dy_see: 54.0
shot_halt: 3.0
see_halt: 3.0
shot_halt: 15
>>>>>>> a65625c36abb3fe40998778ed62788f1eddf865f
