headingangle_compass: 70.0
dx_shot: 0.0
dy_shot: 30.0
dx_see: 0.0
dy_see: 54.0
shot_halt: 4.5
shot_halt_surround: 3.0
shot_halt_low: 1.8
see_halt: 3.5
drone_to_camera_x: 0.0
drone_to_camera_y: 0.16
drone_to_camera_z: 0.20
servo_open_position: 1980
servo_close_position: 1200
