headingangle_compass: 180.0
# headingangle_real: 263.0 # 限定投弹区域有效位置范围的实际角度，不设置默认为headingangle_compass
dx_shot: 0.0
dy_shot: 30.0
dx_see: 0.0
dy_see: 54.7
shot_halt: 4.5
shot_halt_surround: 3.0
shot_halt_low: 1.8
see_halt: 3.5
drone_to_camera_x: -0.057 # 2
drone_to_camera_y: 0.28   # 2
drone_to_camera_z: 0.36   # 2

# drone_to_camera_x: -0.045 # 1
# drone_to_camera_y: 0.30   # 1
# drone_to_camera_z: 0.30   # 1 0.20

servo_open_position: 1980
servo_close_position: 1200
shot_big_target: true