limits:
  accel_max_xy: 1.2
  accel_max_yaw: 0.1
  accel_max_z: 0.6
  speed_max_xy: 2.0
  speed_max_yaw: 0.3
  speed_max_z: 0.5
mypid:
  d: 0.0054
  dff: 0
  ff: 0
  i: 0.1875
  integrallimit: 1.3859
  outputlimit: 2.0217
  p: 0.6277
pos_x:
  p: 0.2
  i: 0.08
  d: 0.10
  dff: 0
  ff: 0
  imax: 5
pos_y:
  p: 0.2
  i: 0.08
  d: 0.10
  dff: 0
  ff: 0
  imax: 5
pos_yaw:
  p: 0.1
  i: 0.01
  d: 0.005
  dff: 0
  ff: 0
  imax: 5
pos_z:
  p: 0.1
  i: 0.01
  d: 0.005
  dff: 0
  ff: 0
  imax: 10
pos_px:
  d: 0
  dff: 0
  ff: 0
  i: 0
  imax: 10
  p: 1
pos_py:
  d: 0
  dff: 0
  ff: 0
  i: 0
  imax: 10
  p: 1
pos_pz:
  d: 0
  dff: 0
  ff: 0
  i: 0
  imax: 10
  p: 1
pos_vx:
  d: 0.85
  dff: 0
  ff: 0
  i: 1.15
  imax: 10
  p: 1.35
pos_vy:
  d: 0.85
  dff: 0
  ff: 0
  i: 1.15
  imax: 10
  p: 1.35
pos_vz:
  d: 0
  dff: 0
  ff: 0
  i: 0
  imax: 10
  p: 1