pid:
  p: 0.085 #0.160 #0.165 #0.080 #0.170
  i: 0.050 #0.035 #0.055 #0.050 #0.065
  d: 0.105 #0.030 #0.055 #0.125 #0.068
  ff: 0
  dff: 0
  imax: 0.05
limits:
  speed_max_xy: 0.7
  speed_max_z: 0.15
  speed_max_yaw: 0.05 
  accel_max_xy: 0.5
  accel_max_z: 0.1

shot_duration: 2.0   # 投弹持续时间 单位：s
shot_wait: 0.5       # 投弹后等待时间 单位：s
accuracy: 0.0065   # 0.60 使用像素半径作为目标范围的百分比 * radius 单位：1
radius: 0.080      # 到达目标范围内的精度 单位：m

tar_x_l: 665.0     # z=1.2m 左侧舵机 目标x坐标，单位：px  0使用默认值
tar_y_l: 470.0     # z=1.2m 左侧舵机 目标y坐标，单位：px  0使用默认值
tar_z_l: 1.0         # 目标z坐标 单位：m
tar_x_r: 615.0     # z=1.2m 右侧舵机 目标x坐标，单位：px  0使用默认值
tar_y_r: 470.0     # z=1.2m 右侧舵机 目标y坐标，单位：px  0使用默认值
tar_z_r: 1.0         # 目标y坐标 单位：m
shot_target_x_l: -0.048  # 2 0.045 #0.130   # 0.045 # 左侧舵机 相对于飞机坐标 投弹点x坐标，单位：m
shot_target_y_l: 0.01   # 2 左侧舵机 投弹点y坐标，单位：m
shot_target_z_l: 0.07    # 未使用 2 左侧舵机 投弹点z坐标，单位：m
shot_target_x_r: 0.048   # 2 -0.045 #0.103  # -0.045 # 右侧舵机 投弹点
shot_target_y_r: 0.01  # 2 右侧舵机 投弹点y坐标，单位：m
shot_target_z_r: 0.07    # 未使用 2 右侧舵机 投弹点 z坐标，单位：m

# shot_target_x_l: -0.085  # 1 0.045 #0.130   # 0.045 # 左侧舵机 相对于飞机坐标 投弹点x坐标，单位：m
# shot_target_y_l: -0.003  # 1 左侧舵机 投弹点y坐标，单位：m
# shot_target_z_l: 0.0     # 1 左侧舵机 投弹点z坐标，单位：m
# shot_target_x_r: 0.085   # 1 -0.045 #0.103  # -0.045 # 右侧舵机 投弹点
# shot_target_y_r: 0.003   # 1 右侧舵机 投弹点y坐标，单位：m
# shot_target_z_r: 0.0     # 1 右侧舵机 投弹点 z坐标，单位：m 0.32

pos_pid:
  p: 0.080 #0.160 #0.165
  i: 0.050 #0.035 #0.055
  d: 0.125 #0.030 #0.055
  ff: 0
  dff: 0
  imax: 0.1
