pid:
  p: 0.165 #0.160 #0.165
  i: 0.055 #0.035 #0.055
  d: 0.055 #0.030 #0.055
  ff: 0
  dff: 0
  imax: 0.1
limits:
  speed_max_xy: 0.7
  speed_max_z: 0.15
  speed_max_yaw: 0.05
  accel_max_xy: 0.5
  accel_max_z: 0.1

accuracy: 0.80   # 使用像素半径作为目标范围的百分比 单位：1
radius: 0.080      # 到达目标范围内的精度 单位：m

tar_x_l: 700.0     # 左侧舵机 目标x坐标，单位：px  0使用默认值
tar_y_l: 450.0     # 左侧舵机 目标y坐标，单位：px  0使用默认值
tar_z_l: 1.2         # 目标z坐标 单位：m
tar_x_r: 620.0     # 右侧舵机 目标x坐标，单位：px  0使用默认值
tar_y_r: 450.0     # 右侧舵机 目标y坐标，单位：px  0使用默认值
tar_z: 1.2         # 目标y坐标 单位：m
shot_target_x_l: -0.070  # 2 0.045 #0.130   # 0.045 # 左侧舵机 相对于飞机坐标 投弹点x坐标，单位：m
shot_target_y_l: 0.001   # 2 左侧舵机 投弹点y坐标，单位：m
shot_target_z_l: 0.10    # 2 左侧舵机 投弹点z坐标，单位：m
shot_target_x_r: 0.070   # 2 -0.045 #0.103  # -0.045 # 右侧舵机 投弹点
shot_target_y_r: -0.001  # 2 右侧舵机 投弹点y坐标，单位：m
shot_target_z_r: 0.10    # 2 右侧舵机 投弹点 z坐标，单位：m

# shot_target_x_l: -0.085  # 1 0.045 #0.130   # 0.045 # 左侧舵机 相对于飞机坐标 投弹点x坐标，单位：m
# shot_target_y_l: -0.003  # 1 左侧舵机 投弹点y坐标，单位：m
# shot_target_z_l: 0.0     # 1 左侧舵机 投弹点z坐标，单位：m
# shot_target_x_r: 0.085   # 1 -0.045 #0.103  # -0.045 # 右侧舵机 投弹点
# shot_target_y_r: 0.003   # 1 右侧舵机 投弹点y坐标，单位：m
# shot_target_z_r: 0.0     # 1 右侧舵机 投弹点 z坐标，单位：m 0.32
